### ISSUE TITLE
please update the submodule of BehaviorTree.CPP to 561f4fa86b45c64c9bb2fd3273f81363e6fd222f(latest master)

### ISSUE THREAD

**Issue by kintzhao** [BehaviorTree/Groot#86]
yhzhao@yhzhao:~/test_git/Groot/build$ git submodule  update  --init --recursive 
Submodule 'depend/BehaviorTree.CPP' (https://github.com/BehaviorTree/BehaviorTree.CPP/) registered for path '../depend/BehaviorTree.CPP'
Cloning into 'depend/BehaviorTree.CPP'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 7910 (delta 23), reused 72 (delta 16), pack-reused 7820
Receiving objects: 100% (7910/7910), 5.80 MiB | 337.00 KiB/s, done.
Resolving deltas: 100% (5405/5405), done.
Checking connectivity... done.
Submodule path '../depend/BehaviorTree.CPP': checked out '23c6957db095ce6e7271c3e8977d743a71c3a001'

---> but has error on make 
yhzhao@yhzhao:~/test_git/Groot/build$ cmake ..
CMake Warning at CMakeLists.txt:65 (find_package):
  By not providing "FindBehaviorTree.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "BehaviorTree", but CMake did not find one.

  Could not find a package configuration file provided by "BehaviorTree" with
  any of the following names:

    BehaviorTreeConfig.cmake
    behaviortree-config.cmake

  Add the installation prefix of "BehaviorTree" to CMAKE_PREFIX_PATH or set
  "BehaviorTree_DIR" to a directory containing one of the above files.  If
  "BehaviorTree" provides a separate development package or SDK, be sure it
  has been installed.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- ZeroMQ found.
-- Found GTest: /usr/lib/libgtest.a  
-- BEHAVIOR_TREE_LIB_DESTINATION:   lib 
-- BEHAVIOR_TREE_BIN_DESTINATION:   bin 
-- CMAKE_RUNTIME_OUTPUT_DIRECTORY:  /home/yhzhao/test_git/Groot/build/bin 
-- CMAKE_LIBRARY_OUTPUT_DIRECTORY:  /home/yhzhao/test_git/Groot/build/lib 
-- CMAKE_ARCHIVE_OUTPUT_DIRECTORY:  /home/yhzhao/test_git/Groot/build/bin 
-- ZeroMQ found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yhzhao/test_git/Groot/build
yhzhao@yhzhao:~/test_git/Groot/build$ make -j4 
Scanning dependencies of target behavior_tree_editor_automoc
Scanning dependencies of target QtNodeEditor_automoc
Scanning dependencies of target Groot_automoc
Scanning dependencies of target behaviortree_cpp_v3_automoc
[  1%] Automatic moc, uic and rcc for target QtNodeEditor
[  2%] Automatic moc, uic and rcc for target Groot
[  2%] Automatic moc, uic and rcc for target behavior_tree_editor
[  2%] Automatic moc, uic and rcc for target behaviortree_cpp_v3
Generating ui_custom_node_dialog.h
[  2%] Built target QtNodeEditor_automoc

```````

[ 76%] Building CXX object CMakeFiles/behavior_tree_editor.dir/bt_editor/bt_editor_base.cpp.o
[ 77%] Building CXX object CMakeFiles/behavior_tree_editor.dir/bt_editor/graphic_container.cpp.o
/home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp: In lambda function:
/home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp:195:34: error: ‘SubtreeNode’ is not a member of ‘BT’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                  ^
/home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp:195:34: error: ‘SubtreeNode’ is not a member of ‘BT’
/home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp:195:57: error: no matching function for call to ‘BT::BehaviorTreeFactory::registerNodeType(const char [5])’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                                         ^
In file included from /home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.h:11:0,
                 from /home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp:1:
/home/yhzhao/test_git/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note: candidate: template<class T> void BT::BehaviorTreeFactory::registerNodeType(const string&)
     void registerNodeType(const std::string& ID)
          ^
/home/yhzhao/test_git/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note:   template argument deduction/substitution failed:
/home/yhzhao/test_git/Groot/bt_editor/bt_editor_base.cpp:195:57: error: template argument 1 is invalid
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                                         ^
CMakeFiles/behavior_tree_editor.dir/build.make:214: recipe for target 'CMakeFiles/behavior_tree_editor.dir/bt_editor/bt_editor_base.cpp.o' failed
make[2]: *** [CMakeFiles/behavior_tree_editor.dir/bt_editor/bt_editor_base.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/behavior_tree_editor.dir/all' failed
make[1]: *** [CMakeFiles/behavior_tree_editor.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2



---------------------
it is build ok  when update the submodule of BehaviorTree.CPP to 561f4fa86b45c64c9bb2fd3273f81363e6fd222f(latest master)

**Comment by facontidavide** [comment]
done
